apiVersion: v1
kind: Secret
metadata:
  name: payment
  namespace: roboshop
  labels:
    component: payment
    project: roboshop
    tier: backend 
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: "cm9ib3Nob3AK"
  RABBITMQ_DEFAULT_PASS: "cm9ib3Nob3AxMjMK"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment
  namespace: roboshop
  labels: 
    component: payment
    project: roboshop
    tier: backend
data: 
  CART_HOST: "cart"
  CART_PORT: "8080"
  USER_HOST: "user"
  USER_PORT: "8080"
  AMQP_HOST: "rabbitmq"
    
---
apiVersion: app/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
    # deployment labels
  labels:
    component: payment
    project: roboshop
    tier: backend
spec:
  replicaset: 1
  # These are the labels replica set use to create pod replicas, this should match pod labels then only replicas will created
  selector:
    matchLabels:
      component: payment
      project: roboshop
      tier: backend
  # This is pod definition
  template:
    metadata:
      # Pod labels
      labels:
        component: payment
        project: roboshop
        tier: backend
    spec: 
      containers:
      - name: payment
        image: gsurendhar/payment:v2
        envFrom:
        - configMapRef:
            name: payment
        - secretRef:
            name: payment

---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop
  labels:
    component: payment
    project: roboshop
    tier: backend    
spec:
  # These are the labels is use attach pod to service, this should exactly match pod labels then only pods are attached to service
  selector: 
    component: payment
    project: roboshop
    tier: database
  ports:
    protocol: "TCP"
    port: 8080   # service port
    targetPort: 8080    # container port
