apiVersion: app/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
    # deployment labels
  labels:
    component: cart
    project: roboshop
    tier: backend
spec:
  replicaset: 1
  # These are the labels replica set use to create pod replicas, this should match pod labels then only replicas will created
  selector:
    matchLabels:
      component: cart
      project: roboshop
      tier: backend
  # This is pod definition
  template:
    metadata:
      # Pod labels
      labels:
        component: cart
        project: roboshop
        tier: backend
    spec: 
      containers:
      - name: cart
        image: gsurendhar/cart:v2
        envFrom:
        - configMapRef:
            name: cart
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
  labels:
    component: cart
    project: roboshop
    tier: backend    
spec:
  # These are the labels is use attach pod to service, this should exactly match pod labels then only pods are attached to service
  selector: 
    component: cart
    project: roboshop
    tier: database
  ports:
    protocol: "TCP"
    port: 8080   # service port
    targetPort: 8080    # container port
