apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
  labels: 
    component: shipping
    project: roboshop
    tier: backend
data: 
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"
    
---
apiVersion: app/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
    # deployment labels
  labels:
    component: shipping
    project: roboshop
    tier: backend
spec:
  replicaset: 1
  # These are the labels replica set use to create pod replicas, this should match pod labels then only replicas will created
  selector:
    matchLabels:
      component: shipping
      project: roboshop
      tier: backend
  # This is pod definition
  template:
    metadata:
      # Pod labels
      labels:
        component: shipping
        project: roboshop
        tier: backend
    spec: 
      containers:
      - name: shipping
        image: gsurendhar/shipping:v2
        envFrom:
        - configMapRef:
            name: shipping

---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
  labels:
    component: shipping
    project: roboshop
    tier: backend    
spec:
  # These are the labels is use attach pod to service, this should exactly match pod labels then only pods are attached to service
  selector: 
    component: shipping
    project: roboshop
    tier: database
  ports:
    protocol: "TCP"
    port: 8080   # service port
    targetPort: 8080    # container port
