apiVersion: app/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    component: rabbitmq
    project: roboshop
    tier: database
spec:
  replicaset: 1
  selector:
    matchLabels:
      component: rabbitmq
      project: roboshop
      tier: database
  template:
    metadata:
      labels:
        component: rabbitmq
        project: roboshop
        tier: database
    spec: 
      containers:
      - name: rabbitmq
        image: gsurendhar/rabbitmq:v1
        envFrom:
        - secretRef:
            name: rabbitmq
