apiVersion: app/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  labels:
    component: mysql
    project: roboshop
    tier: database
spec:
  replicaset: 1
  selector:
    matchLabels:
      component: mysql
      project: roboshop
      tier: database
  template:
    metadata:
      labels:
        component: mysql
        project: roboshop
        tier: database
    spec: 
      containers:
      - name: mysql
        image: gsurendhar/mysql:v1
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
  labels:
    component: mysql
    project: roboshop
    tier: database    
spec:
  # These are the labels is use attach pod to service, this should exactly match pod labels then only pods are attached to service
  selector: 
    component: mysql
    project: roboshop
    tier: database
  ports:
    protocol: "TCP"
    port: 3306  # service port
    targetPort: 3306  # container port