apiVersion: app/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    component: catalogue
    project: roboshop
    tier: backend
spec:
  replicaset: 1
  selector:
    matchLabels:
      component: catalogue
      project: roboshop
      tier: backend
  template:
    metadata:
      labels:
        component: catalogue
        project: roboshop
        tier: backend
    spec: 
      containers:
      - name: catalogue
        image: gsurendhar/catalogue:v2
