apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
  labels: 
    component: catalogue
    project: roboshop
    tier: backend
data: 
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"
    
---
apiVersion: app/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
    # deployment labels
  labels:
    component: catalogue
    project: roboshop
    tier: backend
spec:
  replicaset: 1
  # These are the labels replica set use to create pod replicas, this should match pod labels then only replicas will created
  selector:
    matchLabels:
      component: catalogue
      project: roboshop
      tier: backend
  # This is pod definition
  template:
    metadata:
      # Pod labels
      labels:
        component: catalogue
        project: roboshop
        tier: backend
    spec: 
      containers:
      - name: catalogue
        image: gsurendhar/catalogue:v2
        envFrom:
        - configMapRef:
            name: catalogue

---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    component: catalogue
    project: roboshop
    tier: backend    
spec:
  # These are the labels is use attach pod to service, this should exactly match pod labels then only pods are attached to service
  selector: 
    component: catalogue
    project: roboshop
    tier: database
  ports:
    protocol: "TCP"
    port: 8080
    targetPort: 8080
