apiVersion: app/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
    # deployment labels
  labels:
    component: user
    project: roboshop
    tier: backend
spec:
  replicaset: 1
  # These are the labels replica set use to create pod replicas, this should match pod labels then only replicas will created
  selector:
    matchLabels:
      component: user
      project: roboshop
      tier: backend
  # This is pod definition
  template:
    metadata:
      # Pod labels
      labels:
        component: user
        project: roboshop
        tier: backend
    spec: 
      containers:
      - name: user
        image: gsurendhar/user:v2
        envFrom:
        - configMapRef:
            name: user
