apiVersion: app/v1
kind: Deployment
metadata:
  name: redis
  namespace: roboshop
  labels:
    component: redis
    project: roboshop
    tier: database
spec:
  replicaset: 1
  selector:
    matchLabels:
      component: redis
      project: roboshop
      tier: database
  template:
    metadata:
      labels:
        component: redis
        project: roboshop
        tier: database
    spec: 
      containers:
      - name: redis
        image: redis:7.0

