apiVersion: app/v1
kind: Deployment
metadata:
  name: redis
  namespace: roboshop
  labels:
    component: redis
    project: roboshop
    tier: database
spec:
  replicaset: 1
  selector:
    matchLabels:
      component: redis
      project: roboshop
      tier: database
  template:
    metadata:
      labels:
        component: redis
        project: roboshop
        tier: database
    spec: 
      containers:
      - name: redis
        image: redis:7.0

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
  labels:
    component: redis
    project: roboshop
    tier: database    
spec:
  # These are the labels is use attach pod to service, this should exactly match pod labels then only pods are attached to service
  selector: 
    component: redis
    project: roboshop
    tier: database
  ports:
    protocol: "TCP"
    port: 6379  # service port
    targetPort: 6379  # container port